import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BokehBackground } from "~/fsd/shared/ui/bokeh-background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-800 text-slate-900 min-h-screen min-w-screen flex flex-col`}
      >
        {/* <BokehBackground /> */}
        <main className="flex-1 flex flex-col items-center justify-center relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}
